/**
 * Standardized API error codes for consistent error handling across frontend and backend.
 * Frontend can use these codes to display user-friendly messages.
 */
export enum ApiErrorCode {
  // General errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',

  // Slot Hold errors
  HOLD_NOT_FOUND = 'HOLD_NOT_FOUND',
  HOLD_EXPIRED = 'HOLD_EXPIRED',
  HOLD_CONFLICT = 'HOLD_CONFLICT',
  HOLD_UNAUTHORIZED = 'HOLD_UNAUTHORIZED',

  // Booking errors
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  BOOKING_ALREADY_EXISTS = 'BOOKING_ALREADY_EXISTS',
  BOOKING_SLOT_UNAVAILABLE = 'BOOKING_SLOT_UNAVAILABLE',
  BOOKING_NOT_CANCELLABLE = 'BOOKING_NOT_CANCELLABLE',
  BOOKING_ALREADY_STARTED = 'BOOKING_ALREADY_STARTED',
  
  // Payment errors
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_ORDER_CREATION_FAILED = 'PAYMENT_ORDER_CREATION_FAILED',
  INSUFFICIENT_WALLET_BALANCE = 'INSUFFICIENT_WALLET_BALANCE',
  AMOUNT_MISMATCH = 'AMOUNT_MISMATCH',

  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Charger errors
  CHARGER_NOT_FOUND = 'CHARGER_NOT_FOUND',
  CHARGER_OFFLINE = 'CHARGER_OFFLINE',
  CONNECTOR_NOT_FOUND = 'CONNECTOR_NOT_FOUND',
  CONNECTOR_UNAVAILABLE = 'CONNECTOR_UNAVAILABLE',
}